SYS AS SYSDBA;

# CREATEING NEW USER

CREATE USER VAMSHA1 IDENTIFIED BY vamshaA;

# CONNECTING

CONN VAMSHA1/VAMSHAA;

SYS AS SYSDBA;

# GRANTING PERVILAGE

GRANT ALL PRIVLAGE TO VAMSHA1;

#CHANGE USER PASSWORD

# U HAVE TO HAVE ACCOUNT FOR THAT

ALTER USER { NAME } IDENTIFIED BY {NEW USER PASSWORD};

# LOCK A USER ACCONT

ALTER USER {USERNAME} ACCOUNT LOCK;

# UNLOCK A USER ACCONT

ALTER USER {USERNAME} ACCONT UNLOCK;

# DROP USER

DROP USER {USERNAME};

# TO SEE TABLE

DESC {TABLENAME};

########################## DDL

# CREATE NEW TABLE

CREATE TABLE {TABLE NAME} (
    COLUMNAME DATATYPE SIZE,
    COLUMNAME2 DATATYPE SIZE
);

# ADD OR REMOVE COLUM

ALTER TABLE {TABLENAME} ADD (COLUMNAME DATATYPE SIZE, COLUMNAME2 DATATYPE SIZE);

# MODIFY COLUM TO CHANGE SOMETHING

ALTER TABLE {TABLENAME} MODIFY (COLUMNAME DATATYPE SIZE, COLUMNAME2 DATATYPE SIZE);

# RENAME COLUM

ALTER TABLE {TABLENAME} RENAME COLUM [OLDNAME] TO [NEWNAME];

################################# DDL

# INSERT DATA INTO TABLE

INSERT INTO {TABLENAME} (
    COLUMNAME DATATYPE SIZE
) VALUES (
    ROW1,
    # IF YOU WANT TO INSERT DATA SPECIFICLY ROW2,
    # ROW3
);

#

-----------------------------------------------------------------------
INSET INTO {TABLENAME} VALUES (

ROW 1,

ROW 2, # YOU KNOW HOW TABLE IS MADE

ROW 3

);

# UPDATE DATA

UPDATE {TABLENAME}
SET
    {COLUM NAME} = "value"
WHERE
    {CONDITION};

# DELETE DATA

DELETE FROM {TABLENAME}
WHERE
    [CONDITION];

# DELETE DATA ONLY

TRUNCATE TABLE {TABELNAME};

# MUST COMMIT BEFORE EXISTING;

COMMIT;