-- GROUP BY : min, max, sum, avg, stddev, variance

USERNAME    :   HR      -- CONNECT TO HR ACCOUNT
PASSWORD    :   HR

-- IF NOT UNLOCKED THEN UNLOCK IT FIRST IF ACCOUNT IS LOCKED
SYS AS SYSDBA
ALTER USER HR IDENTIFIED BY HR;
ALTER USER HE ACCOUNT UNLOCK;


SELECT MAX(SALARY) FROM EMPLOYEES;
/* SELECT FIRST_NAME, MAX(SALARY) FROM EMPLOYEES;  YOU CANT USE 2 AT ONCE*/

SELECT MAX(LAST_NAME) FROM EMPLOYEES;
SELECT MIN(LAST_NAME) FROM EMPLOYEES;

SELECT DEPARTMENT_ID, SUM(SALARY) FROM EMPLOYEES 
    GROUP BY DEPARTMENT_ID;


SELECT DEPARTMENT_ID, SUM(SALARY) FROM EMPLOYEES 
    WHERE DEPARTMENT_ID < 90
    GROUP BY DEPARTMENT_ID;
/* WHERE SHOULD COME BEFORE GROUP BY */

SELECT DEPARTMENT_ID, SUM(SALARY) FROM EMPLOYEES 
    WHERE DEPARTMENT_ID < 90
    GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID, MAX(SALARY) FROM EMPLOYEES 
    HAVING MAX(SALARY) < 10000
    GROUP BY DEPARTMENT_ID;
/* THIS WILL NOT WORK */

SELECT DEPARTMENT_ID, MAX(SALARY) FROM EMPLOYEES 
    GROUP BY DEPARTMENT_ID 
    HAVING MAX(SALARY) < 10000;
/* HAVING COMES AT LAST, USED AGRIDATE FUNCTION */

SELECT DEPARTMENT_ID, MAX(SALARY) FROM EMPLOYEES 
    GROUP BY DEPARTMENT_ID ;

SELECT DEPARTMENT_ID, MAX(SALARY) FROM EMPLOYEES 
    GROUP BY DEPARTMENT_ID, JOB_ID;
/* TO GET MAX SALARY WITH JOB ID AND DEPARTMENT ID */

/* single line subquery ends here */

/*  sub qureing or multirow subquery  
    USES WITH IN : OR GATE, 
    ANY : OR GATE, 
    ALL : AND GATE
*/

/* Q1 */
SELECT SALARY FROM EMPLOYEES WHERE LAST_NAME = "ABEL";
SELECT FIRST_NAME, LAST_NAME WHERE SALARY > 11000
    ||
    \/

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
    WHERE SALARY > (
        SELECT SALARY FROM EMPLOYEES WHERE LAST_NAME = "ABEL";
    );


/* Q2 */

SELECT JOB_ID FROM EMPLOYEES WHERE EMPLOYEES_ID = 141
SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEES_ID = 143
        ||
        \/
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES 
    WHERE JOB_ID = (
        SELECT JOB_ID FROM EMPLOYEES WHERE EMPLOYEES_ID = 141
    ) AND SALARY > (
        SELECT SALARY FROM EMPLOYEES WHERE EMPLOYEES_ID = 143
    )


/* Q3 */
SELECT MIN(SALARY) FROM EMPLOYEES
        ||
        \/
SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES 
    WHERE SALARY = (
        SELECT MIN(SALARY) FROM EMPLOYEES
    )


/* Q4 */

SELECT MIN(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID =80;
SELECT DEPARTMENT_ID, MIN(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID; 

        ||
        \/
SELECT DEPARTMENT_ID, MIN(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID HAVING MIN(SALARY)>(
        SELECT JOB_ID FROM EMPLOYEES WHERE DEPARTMENT_ID = 80
); 

/* Q5 */

SELECT SALARY FROM EMPLOYEES WHERE JOB_ID = "IT_PROG";

SELECT FORST_NAME,LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY < ALL(
    SELECT SALARY FROM EMPLOYEES WHERE JOB_ID = "IT_PROG";
)


/* Q6 */

SELECT FORST_NAME,LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY < ANY(
    SELECT SALARY FROM EMPLOYEES WHERE JOB_ID = "IT_PROG";
)


/* Q7 */

SELECT FORST_NAME,LAST_NAME, SALARY FROM EMPLOYEES WHERE SALARY = ANY(
    SELECT SALARY FROM EMPLOYEES WHERE JOB_ID = "IT_PROG";
);


/* Q8 */

SELECT MIN(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;


SELECT FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
    WHERE SALARY > ALL(
        SELECT MIN(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
    )